language: python
python:
  - "2.7"
  - "3.4"
  - "3.6"
# command to install dependencies
install:
  - pip install -Ur test_requirements.txt
  - pip install .
# command to run tests
script:
  - pytest neleval/
  - ./shell_tests.sh
  - pip install -r doc/requirements.txt sphinx_rtd_theme && cd doc && make SPHINXOPTS=-W html ; cd ..
  - pyflakes neleval/
after_success:
  - coveralls
